CREATE TABLE `vehicle_tracking_details` (
  `device_imei_code` varchar(30) NOT NULL,
  `device_code` varchar(20) DEFAULT 'NA',
  `namespace_code` varchar(20) DEFAULT 'NA',
  `device_time` bigint NOT NULL,
  `datetime` bigint NOT NULL,
  `live_data_flag` tinyint NOT NULL,
  `gps_status_flag` tinyint NOT NULL DEFAULT '0',
  `latitude` float NOT NULL,
  `longitude` float NOT NULL,
  `altitude` float NOT NULL,
  `speed` float NOT NULL,
  `direction` int NOT NULL,
  `odometer` float NOT NULL,
  `gps_move_status` tinyint NOT NULL DEFAULT '0',
  `gsm_signal` tinyint NOT NULL,
  `ignition` tinyint NOT NULL,
  `sequence_number` int NOT NULL,
  `climatize` tinyint NOT NULL,
  `battery_volt` varchar(15) NOT NULL DEFAULT 'NA',
  `location_address_code` varchar(20) NOT NULL DEFAULT 'NA',
  `active_flag` tinyint NOT NULL DEFAULT '1',
  `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `inx_vehicle_tracking_details_1` (`namespace_code`,`device_code`,`device_time`,`active_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
